---
title: "Untitled"
author: "Travis Pritchadrd"
date: '`r Sys.Date()`'
output: html_document
---

```{r map_data, echo=FALSE, message = FALSE, warning=FALSE, results='hide'}

# url <- parse_url("https://services.arcgis.com/uUvqNMGPm7axC2dD/ArcGIS/rest/services")
# 
# url$path <- paste(url$path, "IR_2024_StateFinal/FeatureServer/4/query", sep = "/")
# 
# url$query <- list(where =  paste0("AU_ID= '", params$AU_ID, "'"),
#                   outFields = "*",
#                   returnGeometry = "true",
#                   f = "geojson")
# 

# request <- build_url(url)


requested_AU <- river_stream_GIS %>%
  filter(AU_ID == params$AU_ID) |> 
   mutate(Impaired_parameters = case_when(is.na(Cat_4_parameters) ~ Cat_5_parameters,
                                         is.na(Cat_5_parameters) ~ Cat_4_parameters,
                                                            TRUE ~ str_c(Cat_5_parameters, Cat_4_parameters, sep = ', '))) |> 
   mutate( Cat_5_parameters  = ifelse(is.na(Cat_5_parameters), "", Cat_5_parameters),
            Cat_4_parameters  = ifelse(is.na(Cat_4_parameters), "", Cat_4_parameters),
          Attaining_parameters  = ifelse(is.na(Attaining_parameters), "", Attaining_parameters),
        
         Insufficient_parameters  = ifelse(is.na(Insufficient_parameters), "", Insufficient_parameters),
         )


```

------------------------------------------------------------------------


```{r, map, fig.cap=paste("Map of Assessment Unit")}


pal <-  colorFactor(c("#01856f", "#9a00c4", '#d5b502'), c("Impaired", "Attaining", "Insufficient Data"))
requested_AU %>%
  leaflet() %>%
 # addTiles() %>%
  addProviderTiles(providers$Esri.WorldStreetMap, group = "Street") %>%
  addProviderTiles(providers$Esri.WorldImagery, group = "Satellite") %>%
  leaflet::addWMSTiles("https://basemap.nationalmap.gov/arcgis/services/USGSHydroCached/MapServer/WmsServer",
                       group = "Hydrography",
                       #options = leaflet::WMSTileOptions(format = "image/png",
                                                        # transparent = TRUE,
                                                         #pane = "hydroTiles"),
                       layers = "0") %>%
  addPolylines(data = requested_AU,
               color = ~ pal(AU_status),
               weight = 3,
               opacity = 1,
               popup = paste(
                 "<h3>", requested_AU$AU_Name,"</h3>",
                 '<hr class="dashed">',
                 "<strong> Impaired parameters:</strong>", requested_AU$Impaired_parameters, "<br>",
                 "<br>",
                 "<strong>Attaining parameters:</strong>", requested_AU$Attaining_parameters, "<br>",
                 "<br>",
                 "<strong>Insufficient parameters:</strong>", requested_AU$Insufficient_parameters, "<br>"
               )) %>%
  
  
  addLayersControl(
    baseGroups = c("Street", "Satellite", 'Hydrography'),
    #overlayGroups = c("Hydrography"),
    options = layersControlOptions(collapsed = FALSE)
  ) %>%
  addLegend("bottomright", pal = pal, values = ~ c("Impaired", "Attaining", "Insufficient Data"), title = "IR Status") 
```
