---
title: "Untitled"
author: "Travis Pritchadrd"
date: '`r Sys.Date()`'
output: html_document
---

```{r map_data, echo=FALSE, message = FALSE, warning=FALSE, results='hide'}

url <- parse_url("https://services.arcgis.com/uUvqNMGPm7axC2dD/ArcGIS/rest/services")

url$path <- paste(url$path, "IR_2022_StateFinal/FeatureServer/13/query", sep = "/")

url$query <- list(where = "AU_ID = 'OR_WS_170900030603_02_104290'",
                  outFields = "*",
                  returnGeometry = "true",
                  f = "geojson")

request <- build_url(url)


requested_AU <- st_read(request)

url <- parse_url("https://services.arcgis.com/uUvqNMGPm7axC2dD/ArcGIS/rest/services")

url$path <- paste(url$path, "IR_2022_StateFinal/FeatureServer/12/query", sep = "/")
url$query <- list(where = "AU_ID = 'OR_WS_170900030603_02_104290'",
                  outFields = "*",
                  returnGeometry = "true",
                  f = "geojson")

request <- build_url(url)



requested_AU_GNIS <- st_read(request) %>%
  mutate(Attaining_parameters = Category_2_Pollutants,
         Impaired_parameters = paste(coalesce(Category_5_Pollutants, ""),
                                     coalesce(Category_4_Pollutants, ""),
                                     coalesce(Category_4A_Pollutants, ""),
                                     coalesce(Category_4B_Pollutants, ""),
                                     coalesce(Category_4C_Pollutants, "")),
         Insufficient_parameters = paste(coalesce(Category_3_Pollutants, ""), 
                                     coalesce(Category_3B_Pollutants, ""),
                                     coalesce(Category_3C_Pollutants, ""),
                                     coalesce(Category_3D_Pollutants, ""))) %>%
  mutate(Attaining_parameters  = ifelse(is.na(Attaining_parameters), "", Attaining_parameters),
         Impaired_parameters  = ifelse(is.na(Impaired_parameters), "", Impaired_parameters),
         Insufficient_parameters  = ifelse(is.na(Insufficient_parameters), "", Insufficient_parameters))
```

------------------------------------------------------------------------

```{r, map, fig.cap=paste("Assessment Unit overall status")}


pal <-  colorFactor(c("#01856f", "#9a00c4", '#d5b502'), c("Impaired", "Attaining", "Insufficient Data"))

requested_AU %>%
  leaflet() %>%
  addTiles() %>%
  addPolygons(color = ~ pal(AU_status),
              opacity = 0,
              fillOpacity = 0.15,
              popup = paste(
                "<h3>", requested_AU$AU_ID,"</h3>",
                '<hr class="dashed">',
                "<strong> Impaired parameters:</strong>", requested_AU$Impaired_parameters, "<br>",
                "<br>",
                "<strong>Attaining parameters:</strong>", requested_AU$Attaining_parameters, "<br>",
                "<br>",
                "<strong>Insufficient parameters:</strong>", requested_AU$Insufficient_parameters, "<br>"
              )) %>%
  addPolylines(data = requested_AU_GNIS,
               color = ~ pal(GNIS_status),
               dashArray = '5',
               weight = 3,
               opacity = 1,
               popup = paste(
                 "<h3>", requested_AU_GNIS$AU_GNIS_Name,"</h3>",
                 '<hr class="dashed">',
                 "<strong> Impaired parameters:</strong>", requested_AU_GNIS$Impaired_parameters, "<br>",
                 "<br>",
                 "<strong>Attaining parameters:</strong>", requested_AU_GNIS$Attaining_parameters, "<br>",
                 "<br>",
                 "<strong>Insufficient parameters:</strong>", requested_AU_GNIS$Insufficient_parameters, "<br>"
               ))%>%
  addLegend("bottomright", pal = pal, values = ~ c("Impaired", "Attaining", "Insufficient Data"), title = "IR Status") 
```